name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.0.43
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.0+4

dev_dependencies:
  test: ^1.14.2
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
